### ISSUE TITLE
Double dot (..) in REPL cause segmentation fault

### ISSUE THREAD

**Issue by dram** [trealla-lang/trealla#19] opened 2016-11-28 07:42 UTC
Double dot (`..`) in REPL will cause segmentation fault, e.g.:

```
% ./tpl 
Trealla v0.1alpha, 64-bits (int=128-bits), Nov 28 2016
?- abc..
Segmentation fault
```

**Comment by infradig** [comment] 2016-11-28 10:40
This was caused by fix for #16. The fix is in the pipeline...

**Closed by infradig** 2016-11-28 10:40 UTC

**Comment by dram** [comment] 2016-11-28 11:19
OK, no hurry. :)
